//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasaProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CasaProduct()
        {
            this.CasaAccounts = new HashSet<CasaAccount>();
        }
    
        public string ProductCode { get; set; }
        public string TypeOfAccount { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> MinimumDeposit { get; set; }
        public Nullable<decimal> MinimumBalance { get; set; }
        public Nullable<decimal> HoldAmount { get; set; }
        public Nullable<decimal> Divisor { get; set; }
        public Nullable<decimal> TaxFactor { get; set; }
        public string ComputeFrequency { get; set; }
        public Nullable<decimal> ServiceChargeActive { get; set; }
        public Nullable<decimal> ServiceChargeDormant { get; set; }
        public Nullable<int> DaysDormant { get; set; }
        public Nullable<int> Terms { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CasaAccount> CasaAccounts { get; set; }
    }
}
