//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanLedger
    {
        public Nullable<int> LoanAccountId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string ReferenceNumber { get; set; }
        public string TransactionType { get; set; }
        public string Description { get; set; }
        public string PrincipalBeginning { get; set; }
        public Nullable<decimal> Principal { get; set; }
        public Nullable<decimal> PrincipalEnding { get; set; }
        public string InterestBeginning { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<decimal> InterestEnding { get; set; }
        public Nullable<decimal> Penalty { get; set; }
        public int id { get; set; }
    
        public virtual LoanAccount LoanAccount { get; set; }
    }
}
