//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Portal_DBEntities : DbContext
    {
        public Portal_DBEntities()
            : base("name=Portal_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barangay> Barangays { get; set; }
        public virtual DbSet<CityMunicipality> CityMunicipalities { get; set; }
        public virtual DbSet<LoanApplication> LoanApplications { get; set; }
        public virtual DbSet<MembershipPaymentFee> MembershipPaymentFees { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<CIFOnlineUser> CIFOnlineUsers { get; set; }
        public virtual DbSet<CasaAccount> CasaAccounts { get; set; }
        public virtual DbSet<CasaLedger> CasaLedgers { get; set; }
        public virtual DbSet<CasaProduct> CasaProducts { get; set; }
        public virtual DbSet<LoanAccount> LoanAccounts { get; set; }
        public virtual DbSet<LoanProductsMaster> LoanProductsMasters { get; set; }
        public virtual DbSet<rptsrc_StatementofAccountLoans> rptsrc_StatementofAccountLoans { get; set; }
        public virtual DbSet<rptsrc_StatementofAccountSavings> rptsrc_StatementofAccountSavings { get; set; }
        public virtual DbSet<MemberAddress> MemberAddresses { get; set; }
        public virtual DbSet<MemberDependent> MemberDependents { get; set; }
        public virtual DbSet<MemberFamily> MemberFamilies { get; set; }
        public virtual DbSet<Membership> Memberships { get; set; }
        public virtual DbSet<MembershipPayment> MembershipPayments { get; set; }
        public virtual DbSet<LoanLedger> LoanLedgers { get; set; }
    }
}
